### ISSUE TITLE
 The build of the eviction set is not always successful

### ISSUE THREAD

**Issue by Yujie-Cui** [KULeuven-COSIC/PRIME-SCOPE#3]
Thank you very much for open source. But I found that the build of the eviction set is not always successful
It may take many tries before succeeding once or twice.  I run it in Intel(R) Xeon(R) CPU E5-2609 v4 server.

may I ask if this is normal?

1. I found that in the original code, the result of the threshold calculation shows that the access time of RAM is almost the same as LLC. This should be problematic. I modified the function of threshold calculation. Based on this threshold, I modified your code to support flush+reload, and it was successful. It shows that the threshold is obtained correctly. But now eviction build are not always successful. He sometimes will get stuck in the _goto repeat_evset; position_ 。
(I have modified _traverse_list_asm_skylake_ to _traverse_list_asm_simple_ to fit my machine.)

2. And I found a very annoying problem. Sometimes accessing all cache lines in guess_pool does not guarantee that the victim will be evicted (it may take many times to succeed).

         maccess((void*)victim);
          asm volatile("lfence;mfence");
          for(int i=0;i<**MAX_POOL_SIZE**;i++){
                maccess((void*)guess_pool[i]);
                asm volatile("lfence");
          }
          time = time_mread((void*)victim);

I also have a cloud server. But its LLC size is not an integer.
LEVEL1_ICACHE_SIZE                 32768
LEVEL1_ICACHE_ASSOC                8
LEVEL1_ICACHE_LINESIZE             64
LEVEL1_DCACHE_SIZE                 32768
LEVEL1_DCACHE_ASSOC                8
LEVEL1_DCACHE_LINESIZE             64
LEVEL2_CACHE_SIZE                  1048576
LEVEL2_CACHE_ASSOC                 16
LEVEL2_CACHE_LINESIZE              64
LEVEL3_CACHE_SIZE                  37486592
LEVEL3_CACHE_ASSOC                 11
LEVEL3_CACHE_LINESIZE              64

**lscpu**
L1d cache:                       384 KiB
L1i cache:                       384 KiB
L2 cache:                        12 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0-23

In this case, how to calculate the number of cache sets of its LLC?  37486592/64/11/24 is not an integer.

thank you very much!
Best regards

**Comment by furkanturan** [comment]
Hello Yujie-Cui,

Thanks for interest in Prime+Scope. 

First of all, I want to state that we do not have access to a Xeon CPU E5-2609 v4, or a similar one with a large inclusive LLC to test it ourselves and give you a precise answer.

When reading your message, the first thing we suspected was the possibility of mis-configuration. For example, you mentioned problems in threshold calculation. The code handles this calculation differently for inclusive and non-inclusive cases. Might you be using non-inclusive configuration, instead of inclusive? 

Also you mention that 
>Sometimes accessing all cache lines in guess_pool does not guarantee that the victim will be evicted

As you said "sometimes", this again sounds like an issue that might be improved with some tweaks in the configuration. For example, if `guess_pool` cannot evict the victim, then there is not an eviction set within the pool. Maybe that is an item to look into, for example, increasing the pool size? Also, have you played with the `MAX_EXTENSION` and `MAX_ATTEMPT` variables?
___

For the second part of the question, you mentioned another server without giving its processor information. By looking at the cache information you shared, I guess you have something similar to a Platinum 8260.

[According to WikiCkip](https://en.wikichip.org/wiki/intel/xeon_platinum/8260), L3 is 37.75 MiB, with slices each is 1.375 MiB, and 11-way set associativity. There are 24 cores, but 26 slices. Hence, you should calculate LLC set size with 26.

* In the lscpu dump you see L3 cache size is: 37486592 bytes
* As you have 26 slices, each slice’s size is: 37486592 bytes / 26
* As there are 11 ways on each slice, the size of each way is: 37486592 bytes / 26 / 11
* As cache line is 512-bits, there should be 37486592 bytes / 26 / 11 / 512-bits cache lines for each way

How many cache lines you have for each way, is basically how many sets you have. That is 37486592 bytes / 26 / 11 / 512-bits = 2048. So you should have 2048 sets.

Kind Regards,
Furkan

**Comment by Yujie-Cui** [comment]
I really appreciate your reply. And the code you exposed has been a huge help to me. I've been wanting to try doing some cache channel related work on the LLC. But I haven't been able to have a good way of building an eviction set. It is a pity that the paper “Last-Level Cache Side-Channel Attacks are Practical” is not open source. Your open source code helped me a lot.
I tried it again recently. I found that an eviction set was successfully constructed 7 to 8 times out of 10 on average.


1. I just read the physical addresses of addresses in the eviction set with root privileges and got their LLC index bits. And use the reverse-engineered slice hash function of Maurice et al. to obtain the slice number. The results show that the addresses in the eviction set are in the same slice and the same LLC index.  This should indicate that I'm getting the eviction set correctly.
I'm trying the follow-up. Thank you very much!

Best regards.

**Comment by furkanturan** [comment]
It is good to hear that you succeeded in eviction-set construction and confirmed the set with physical addresses.

For you interest in "Last-Level Cache Side-Channel Attacks are Practical", maybe you can check the open-source side-channel attacks toolbox, [Mastik](https://github.com/Secure-AI-Systems-Group/Mastik).

Kind Regards,
